[package]
name = "winsafe"
version = "0.0.6"
authors = ["Rodrigo Cesar de Freitas Dias <rcesar@gmail.com>"]
description = "Win32 GUI and related APIs in safe, idiomatic Rust."
categories = ["api-bindings", "gui", "os::windows-apis"]
keywords = ["com", "ffi", "gui", "win32", "windows"]
license = "MIT"
repository = "https://github.com/rodrigocfd/winsafe"
readme = "README.md"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE.md", "/README.md"]
edition = "2021"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["aarch64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]
all-features = true

[features]
autom = []
dshow = ["autom", "idl"]
idl = []
shell = []
